version: '3.8'

services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"        # Cassandra CQL port
      - "7000:7000"        # Native transport (cluster internal)
      - "7199:7199"        # JMX monitoring
      - "9160:9160"        # Thrift service (deprecated but still used by some clients)
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_AUTHENTICATOR=PasswordAuthenticator
      - CASSANDRA_AUTHORIZER=AllowAllAuthorizer
      - CASSANDRA_ROLE_MANAGER=FileRoleManager
    volumes:
      - cassandra_data:/var/lib/cassandra
    networks:
      - cassandra_network

volumes:
  cassandra_data:

networks:
  cassandra_network: